NumPy - Numerical python






Advantages of Numpy Arrays:

1.   Allows several mathematical operations
2.   Faster operations





In [1]:
import numpy as np

List vs Numpy - Time taken

In [2]:
from time import process_time

Time taken by a list

In [3]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0043835509999996525


Time taken by a array

In [4]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)

0.00015369099999995584


Numpy arrays

In [7]:
# list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [9]:
np_array = np.array([1,2,3,4,5])

print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [10]:
# creating a 1 dimension array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [11]:
a.shape # number of rows and columns

(4,)

In [12]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [13]:
b.shape

(2, 4)

In [20]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [21]:
c.shape

(2, 4)

Initial placeholders in numpy arrays

In [26]:
# create a numpy array of zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [24]:
# create a numpy array of ones
x = np.ones((4,5))
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [30]:
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [35]:
# create an identity matrix
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [36]:
# create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.92402277 0.44893373 0.17760048 0.62480682]
 [0.9348496  0.6457934  0.38454684 0.37729285]
 [0.64196239 0.71761332 0.73461584 0.41543071]]


In [41]:
# random integer values array within a specific range
c = np.random.randint(1,10, (3,5))
print(c)


[[1 2 2 4 8]
 [8 7 7 9 6]
 [4 6 4 5 7]]


In [54]:
# array of evenly spaced values ---> specifying the number of values required | linspace function includes the stop value | (30-10)/(5-1) = 5 = increment | starts at 10, uses the increment every iteraction and stops at 30
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [56]:
# array of evenly spaced values ---> specifying the step | arange function does not include the stop value | starts at 10, increments 5 every iteraction and stops before reaching 30
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [60]:
# convert a list to a numpy array
list2 = [10,20,20,20,50]
np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

Analysing a numpy array

In [61]:
c = np.random.randint(1,10,(5,5))
print(c)

[[8 3 4 9 5]
 [1 5 8 6 3]
 [2 2 5 4 6]
 [3 3 1 3 6]
 [9 4 9 7 6]]


In [62]:
# array dimension
print(c.shape)

(5, 5)


In [63]:
# number of dimensions
print(c.ndim)

2


In [64]:
# number of elements in an array
print(c.size)

25


In [65]:
# checking the data type of the values in the array
print(c.dtype)

int64


Mathematical operations on a np array

In [66]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2) # concatenate or join two lists

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [72]:
a = np.random.randint(1,10,(3,3))
b = np.random.randint(1,5,(3,3))
print(a)
print(b)
print(a+b) # element wise addition
print(a-b) # element wise subtraction
print(a*b) # element wise multiplication
print(a/b) # element wise division

[[8 6 6]
 [8 4 6]
 [3 1 6]]
[[1 3 3]
 [3 4 2]
 [2 2 2]]
[[ 9  9  9]
 [11  8  8]
 [ 5  3  8]]
[[ 7  3  3]
 [ 5  0  4]
 [ 1 -1  4]]
[[ 8 18 18]
 [24 16 12]
 [ 6  2 12]]
[[8.         2.         2.        ]
 [2.66666667 1.         3.        ]
 [1.5        0.5        3.        ]]


In [73]:
print(np.add(a,b)) # element wise addition
print(np.subtract(a,b)) # element wise subtraction
print(np.multiply(a,b)) # element wise multiplication
print(np.divide(a,b)) # element wise division

[[ 9  9  9]
 [11  8  8]
 [ 5  3  8]]
[[ 7  3  3]
 [ 5  0  4]
 [ 1 -1  4]]
[[ 8 18 18]
 [24 16 12]
 [ 6  2 12]]
[[8.         2.         2.        ]
 [2.66666667 1.         3.        ]
 [1.5        0.5        3.        ]]


Array manipulation

In [74]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[4 0 2]
 [2 3 2]]
(2, 3)


In [75]:
# transpose matrix
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[4 2]
 [0 3]
 [2 2]]
(3, 2)


In [76]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[6 7 6]
 [6 3 2]]
(2, 3)


In [77]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[6 6]
 [7 3]
 [6 2]]
(3, 2)


In [92]:
# reshaping array
a = np.random.randint(1,10,(2,3))
print(a)
print(a.shape)

[[4 2 5]
 [5 6 7]]
(2, 3)


In [93]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[4 2]
 [5 5]
 [6 7]]
(3, 2)
